version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.14 #
    resource_class: small
    environment: # environment variables for the build itself
      GOPATH: /go 
    working_directory: /go/src/github.com/gnyman/go-test-cache-experiment
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory

      - run:
          name: Set timestamps
          command: |
            perl -e '
            my %attributions;
            my $remaining = 0;
            open IN, "git ls-tree -r --full-name HEAD |" or die;
            while (<IN>) {
                if (/^\S+\s+blob \S+\s+(\S+)$/) {
                    $attributions{$1} = -1;
                }
            }
            close IN;
            $remaining = (keys %attributions) + 1;
            print "Number of files: $remaining\n";
            open IN, "git log -r --root --raw --no-abbrev --date=raw --pretty=format:%h~%cd~ |" or die;
            while (<IN>) {
                if (/^([^:~]+)~([^~]+)~$/) {
                    ($commit, $date) = ($1, $2);
                } elsif (/^:\S+\s+1\S+\s+\S+\s+\S+\s+\S\s+(.*)$/) {
                    if ($attributions{$1} == -1) {
                        $attributions{$1} = "$date";
                        $remaining--;
                        utime $date, $date, $1;
                        if ($remaining % 1000 == 0) {
                            print "$remaining\n";
                        }
                        if ($remaining <= 0) {
                            break;
                        }
                    }
                }
            }
            close IN;'

      - run:
          name: Setup Environment Variables
          command: |
            echo "export GO_VERSION=$(go version|md5) >> $BASH_ENV

      - restore_cache: # restores saved cache if no changes are detected since last run
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-go-cache-{{ .Environment.GO_VERSION }}

      - run:
          name: Run unit tests
          command: |
            go test -v ./...

      - save_cache: # Store cache in the /go/pkg directory
          key: v1-go-cache-{{ .Environment.GO_VERSION }}
          paths:
            - "/go/pkg"
            - "/home/circleci/.cache"
